### PR TITLE
BUGFIX: Use `jest-worker` with `install-types` to fix ENOMEM

### PR DESCRIPTION
**Pull request by HsuTing**
Using `Promise.all` will run the all commands at the same time. It will cause  `ENOMEM` in `circleci` when the project has too many packages.

### CODE REVIEW

**Comment by Romischart** [comment]
Thank you so much for your work @HsuTing!
I'm just thinking if the change is a significant performance loss? Do you think one possible solution could be [worker_threads](https://nodejs.org/dist/latest-v12.x/docs/api/worker_threads.html) to stay fast and also work with many dependencies. However, this would result in the Breaking Change as we must have to manifest on nodejs v12.
What do you think?

**Comment by HsuTing** [comment]
Maybe we can try [this](https://github.com/facebook/jest/tree/master/packages/jest-worker) ?
`jest-worker` can support `node@>=8`  and it can run the unit testing with the parallel mode. However, I did not use `jest-worker` before. Maybe we can try this?

**Comment by HsuTing** [comment]
@Romischart Should I need to modify this `pr`?

**Comment by Romischart** [comment]
> @Romischart Should I need to modify this `pr`?
Yeah, it would be so nice if you want to try it out?
We would be very grateful to you!

**Comment by HsuTing** [comment]
@Romischart I had changed my code with `jest-worker`. It can work to me.

**Comment by Romischart** [comment]
@HsuTing nice work, thank you so much!
I have added an integration test, it would be nice if you can merge master changes again in your branch. When the pipeline succeed i will merge it!

**Comment by Romischart** [comment]
Oh and I see, you musst meet our commit conventions to trigger a new release ;-)
Probably you can change the merge commit, with a prefix like `BUGFIX:`

**Comment by HsuTing** [comment]
@Romischart I have updated my branch and changed the merge commit 😼 .

**Pull request merged**
