### PR TITLE
Support nohoist yarn workspaces

### PR DESCRIPTION
**Pull request by AndrewJack**
Fixes: #91

### CODE REVIEW

**Comment by Inkdpixels** [comment]
Awesome! Thanks a lot @AndrewJack! Just one little nitpick, could you adjust the commit message to adhere to the guidelines listed in the [CONTRIBUTING.md](https://github.com/ImmoweltGroup/flow-mono-cli/blob/master/CONTRIBUTING.md#commit-guidelines-and-semantic-release)? (E.g. "BUGFIX: Support nohoist yarn workspaces"

That way we can merge it ASAP and it will trigger a new minor release as well automatically. Thanks :)

**Comment by AndrewJack** [comment]
Will do 👍

**Comment by AndrewJack** [comment]
@Inkdpixels commit message updated and tests passing

**Comment by Inkdpixels** [comment]
Release is out, thanks a lot Andrew :)

**Comment by AndrewJack** [comment]
Thanks for the library, it has saved me a lot of hassle. 👏

**Pull request merged**
