### PR TITLE
Rename .bin to bin. Fixes installation with yarn@1.12.1.

### PR DESCRIPTION
**Pull request by DylanVann**
With the latest version of yarn the `flow-mono` command is not found.

Looking at other projects most use `bin` instead of `.bin`.
Making that change fixed the command for me.

### CODE REVIEW

**Comment by FezVrasta** [comment]
@kevroadrunner any chance to see this merged today? It's blocking a bit of stuff here :-(

**Comment by kevroadrunner** [comment]
@FezVrasta Sorry, i didn't noticed this issue here. Thank you for PR, i'll have a look into it.

**Comment by kevroadrunner** [comment]
Unfortunately your commit message doesn't contain a release prefix, in this case 'BUGFIX'. This will not trigger a new release mentioned in `CONTRIBUTING.md`.

**Comment by FezVrasta** [comment]
@kevroadrunner 	I'm not the author, but you can merge this PR using the "squash" method and rename the commit.

**Comment by kevroadrunner** [comment]
Thanks for your help! 👍

**Pull request merged**
